# docker-compose.yml
version: '2'
services:
    prometheus:
        build: ./prometheus
        volumes:
            - $PWD/data/prometheus_data:/prometheus
        ports:
            - "9090:9090"
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-alertmanager.url=http://alertmanager:9093'
    node-exporter:
        image: prom/node-exporter:v0.14.0
    grafana:
        image: grafana/grafana:4.5.1
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
        volumes:
            - $PWD/data/grafana_data:/var/lib/grafana
        ports:
            - "3001:3000"
        depends_on:
            - prometheus
    alertmanager:
        build: ./alertmanager
        command:
            - '-config.file=/alertmanager.yml'
volumes:
    prometheus_data: {}
    grafana_data: {}
    letsencrypt: {}
    letsencrypt_backups: {}
    dhparam_cache: {}
