# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'jhidalgo3'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['node-exporter:9100']
rule_files:
    - 'alert.rules'
